---
- hosts: all
  vars:
    home: ""
  tasks:
  - name: Clone git-repo-manager
    ansible.builtin.git:
      repo: git@github.com:theintegrative/git-repo-manager.git
      dest: "{{home}}./git/hub/int/git-repo-manager"
    ignore_errors: yes

  - name: Clone obsidian-system-content
    ansible.builtin.git:
      repo: git@github.com:theintegrative/obsidian-system-content.git
      dest: "{{home}}./git/hub/int/obsidian-system-content"
    ignore_errors: yes

  - name: Clone home-lab-setup
    ansible.builtin.git:
      repo: git@github.com:theintegrative/home-lab-setup.git
      dest: "{{home}}./git/hub/int/home-lab-setup"
    ignore_errors: yes

  - name: Clone scalable-ansible-vagrant-project-template
    ansible.builtin.git:
      repo: git@github.com:theintegrative/scalable-ansible-vagrant-project-template.git
      dest: "{{home}}./git/hub/int/scalable-ansible-vagrant-project-template"
    ignore_errors: yes

  - name: Clone content-vault
    ansible.builtin.git:
      repo: git@github.com:theintegrative/content-vault.git
      dest: "{{home}}./git/hub/int/content-vault"
    ignore_errors: yes

  - name: Clone obsidian-system
    ansible.builtin.git:
      repo: git@github.com:theintegrative/obsidian-system.git
      dest: "{{home}}./git/hub/int/obsidian-system"
    ignore_errors: yes

  - name: Clone scalable-ansible-project-template
    ansible.builtin.git:
      repo: git@github.com:theintegrative/scalable-ansible-project-template.git
      dest: "{{home}}./git/hub/int/scalable-ansible-project-template"
    ignore_errors: yes

  - name: Clone obsidian
    ansible.builtin.git:
      repo: git@github.com:theintegrative/obsidian.git
      dest: "{{home}}./git/hub/int/obsidian"
    ignore_errors: yes

  - name: Clone shell-scripts
    ansible.builtin.git:
      repo: git@github.com:theintegrative/shell-scripts.git
      dest: "{{home}}./git/hub/int/shell-scripts"
    ignore_errors: yes

  - name: Clone ansible-skeleton-role
    ansible.builtin.git:
      repo: git@github.com:theintegrative/ansible-skeleton-role.git
      dest: "{{home}}./git/hub/int/ansible-skeleton-role"
    ignore_errors: yes

  - name: Clone vagrant-project-template
    ansible.builtin.git:
      repo: git@github.com:theintegrative/vagrant-project-template.git
      dest: "{{home}}./git/hub/int/vagrant-project-template"
    ignore_errors: yes

  - name: Clone scalable-ansible-vagrant-gitlab-ci-project-template
    ansible.builtin.git:
      repo: git@gitlab.com:tint-project-templates/scalable-ansible-vagrant-gitlab-ci-project-template.git
      dest: "{{home}}./git/lab/int/scalable-ansible-vagrant-gitlab-ci-project-template"
    ignore_errors: yes

  - name: Clone main-driver-setup
    ansible.builtin.git:
      repo: git@github.com:theintegrative/main-driver-setup.git
      dest: "{{home}}./git/hub/int/main-driver-setup"
    ignore_errors: yes

  - name: Clone gitlab-server
    ansible.builtin.git:
      repo: git@github.com:theintegrative/gitlab-server.git
      dest: "{{home}}./git/hub/int/gitlab-server"
    ignore_errors: yes

  - name: Clone OpenHRV
    ansible.builtin.git:
      repo: git@github.com:JanCBrammer/OpenHRV.git
      dest: "{{home}}./git/hub/ext/OpenHRV"
    ignore_errors: yes

  - name: Clone Straattaal-vertaler
    ansible.builtin.git:
      repo: git@github.com:PimLeerkes/Straattaal-vertaler.git
      dest: "{{home}}./git/hub/ext/Straattaal-vertaler"
    ignore_errors: yes

  - name: Clone brainworkshop
    ansible.builtin.git:
      repo: git@github.com:brain-workshop/brainworkshop.git
      dest: "{{home}}./git/hub/ext/brainworkshop"
    ignore_errors: yes

  - name: Clone rtl8852be
    ansible.builtin.git:
      repo: git@github.com:HRex39/rtl8852be.git
      dest: "{{home}}./git/hub/ext/rtl8852be"
    ignore_errors: yes

  - name: Clone rtl8852be_bt
    ansible.builtin.git:
      repo: git@github.com:HRex39/rtl8852be_bt.git
      dest: "{{home}}./git/hub/ext/rtl8852be_bt"
    ignore_errors: yes

  - name: Clone theintegrative-net-config
    ansible.builtin.git:
      repo: git@gitlab.com:main-website1/theintegrative-net-config.git
      dest: "{{home}}./git/lab/int/theintegrative-net-config"
    ignore_errors: yes

  - name: Clone theintegrative-net
    ansible.builtin.git:
      repo: git@gitlab.com:main-website1/theintegrative-net.git
      dest: "{{home}}./git/lab/int/theintegrative-net"
    ignore_errors: yes

